#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "___________                     ____   ____      .__  .__    .___            ";
$L "\__    ___/___ _____    _____   \   \ /   /____  |  | |__| __| _/_ __  ______";
$L "  |    |_/ __ \\__  \  /     \   \   Y   /\__  \ |  | |  |/ __ |  |  \/  ___/";
$L "  |    |\  ___/ / __ \|  Y Y  \   \     /  / __ \|  |_|  / /_/ |  |  /\___ \ ";
$L "  |____| \___  >____  /__|_|  /    \___/  (____  /____/__\____ |____//____  >";
$L "             \/     \/      \/                 \/             \/          \/ ";
$L "Welcome to Android `getprop ro.build.version.release` / Validus-`getprop ro.validus.version`";
