#!/bin/sh
add_lunch_combo validus_angler-userdebug

add_lunch_combo validus_dlx-userdebug
add_lunch_combo validus_endeavoru-userdebug
add_lunch_combo validus_m8-userdebug

add_lunch_combo validus_d800-userdebug
add_lunch_combo validus_d801-userdebug
add_lunch_combo validus_d802-userdebug
add_lunch_combo validus_d803-userdebug
add_lunch_combo validus_d850-userdebug
add_lunch_combo validus_d851-userdebug
add_lunch_combo validus_d852-userdebug
add_lunch_combo validus_d855-userdebug
add_lunch_combo validus_f320-userdebug
add_lunch_combo validus_f400-userdebug
add_lunch_combo validus_h811-userdebug
add_lunch_combo validus_h815-userdebug
add_lunch_combo validus_ls980-userdebug
add_lunch_combo validus_ls990-userdebug
add_lunch_combo validus_v410-userdebug
add_lunch_combo validus_v500-userdebug
add_lunch_combo validus_vs980-userdebug
add_lunch_combo validus_vs985-userdebug

add_lunch_combo validus_condor-userdebug
add_lunch_combo validus_falcon-userdebug
add_lunch_combo validus_ghost-userdebug
add_lunch_combo validus_mb886-userdebug
add_lunch_combo validus_titan-userdebug

add_lunch_combo validus_deb-userdebug
add_lunch_combo validus_flo-userdebug
add_lunch_combo validus_flounder-userdebug
add_lunch_combo validus_grouper-userdebug
add_lunch_combo validus_hammerhead-userdebug
add_lunch_combo validus_mako-userdebug
add_lunch_combo validus_shamu-userdebug

add_lunch_combo validus_bacon-userdebug
add_lunch_combo validus_oneplus2-userdebug

add_lunch_combo validus_chagallwifi-userdebug
add_lunch_combo validus_d2att-userdebug
add_lunch_combo validus_d2tmo-userdebug
add_lunch_combo validus_hercules-userdebug
add_lunch_combo validus_hlte-userdebug
add_lunch_combo validus_hltespr-userdebug
add_lunch_combo validus_hltetmo-userdebug
add_lunch_combo validus_i9100-userdebug
add_lunch_combo validus_i9300-userdebug
add_lunch_combo validus_lt01wifi-userdebug
add_lunch_combo validus_jflte-userdebug
add_lunch_combo validus_klte-userdebug
add_lunch_combo validus_kltedv-userdebug
add_lunch_combo validus_kminilte-userdebug
add_lunch_combo validus_matissewifi-userdebug
add_lunch_combo validus_n7100-userdebug
add_lunch_combo validus_n8013-userdebug
add_lunch_combo validus_p3110-userdebug
add_lunch_combo validus_quincyatt-userdebug
add_lunch_combo validus_serrano3gxx-userdebug
add_lunch_combo validus_serranoltexx-userdebug
add_lunch_combo validus_skyrocket-userdebug
add_lunch_combo validus_trltetmo-userdebug

add_lunch_combo validus_pollux-userdebug
add_lunch_combo validus_pollux_windy-userdebug
add_lunch_combo validus_sirius-userdebug
add_lunch_combo validus_z3-userdebug
add_lunch_combo validus_z3c-userdebug

add_lunch_combo validus_armani-userdebug
add_lunch_combo validus_cancro-userdebug

add_lunch_combo validus_tomato-userdebug
